
development:
  adapter: postgresql
  encoding: utf8
  database: bloccit_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: bloccit_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: bloccit_production
  host: localhost
  pool: 5
  timeout: 5000
